name: Deploy Website with API Key Injection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Inject API Key into Config
      run: |
        echo "{ \"apiKey\": \"${{ secrets.WEBSITECHATBOT }}\" }" > config.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Adjust to the folder containing your website files
